version: "3.3"
services:

    jeca1:
        build:
            context: .
            dockerfile: lamportMachines/Dockerfile
        image: lamportmachines
        command: 0 0.0.0.0:50051 0.0.0.0:50052 0.0.0.0:50053
        networks:
            - microservices
        ports:
            - 50051:50051
    jeca2:
        build:
            context: .
            dockerfile: lamportMachines/Dockerfile
        image: lamportmachines
        command: 1 0.0.0.0:50051 0.0.0.0:50052 0.0.0.0:50053
        networks:
            - microservices
        ports:
            - 50052:50051
    jeca3:
        build:
            context: .
            dockerfile: lamportMachines/Dockerfile
        image: lamportmachines
        command: 2 0.0.0.0:50051 0.0.0.0:50052 0.0.0.0:50053
        networks:
            - microservices
        ports:
            - 50053:50051


networks:
    microservices:
