# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mutex.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mutex.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmutex.proto\"(\n\x0cMutexMessage\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04time\x18\x02 \x01(\x04\x32=\n\tMutexSend\x12\x30\n\x10\x41skForPermission\x12\r.MutexMessage\x1a\r.MutexMessageb\x06proto3'
)




_MUTEXMESSAGE = _descriptor.Descriptor(
  name='MutexMessage',
  full_name='MutexMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MutexMessage.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='MutexMessage.time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['MutexMessage'] = _MUTEXMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MutexMessage = _reflection.GeneratedProtocolMessageType('MutexMessage', (_message.Message,), {
  'DESCRIPTOR' : _MUTEXMESSAGE,
  '__module__' : 'mutex_pb2'
  # @@protoc_insertion_point(class_scope:MutexMessage)
  })
_sym_db.RegisterMessage(MutexMessage)



_MUTEXSEND = _descriptor.ServiceDescriptor(
  name='MutexSend',
  full_name='MutexSend',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=57,
  serialized_end=118,
  methods=[
  _descriptor.MethodDescriptor(
    name='AskForPermission',
    full_name='MutexSend.AskForPermission',
    index=0,
    containing_service=None,
    input_type=_MUTEXMESSAGE,
    output_type=_MUTEXMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MUTEXSEND)

DESCRIPTOR.services_by_name['MutexSend'] = _MUTEXSEND

# @@protoc_insertion_point(module_scope)
