# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lamport_pb2 as lamport__pb2


class LamportSendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LampSend = channel.unary_unary(
                '/LamportSend/LampSend',
                request_serializer=lamport__pb2.LamportMessage.SerializeToString,
                response_deserializer=lamport__pb2.LamportOK.FromString,
                )


class LamportSendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LampSend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LamportSendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LampSend': grpc.unary_unary_rpc_method_handler(
                    servicer.LampSend,
                    request_deserializer=lamport__pb2.LamportMessage.FromString,
                    response_serializer=lamport__pb2.LamportOK.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LamportSend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LamportSend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LampSend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LamportSend/LampSend',
            lamport__pb2.LamportMessage.SerializeToString,
            lamport__pb2.LamportOK.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
